---
title: "Iteration and Listcols"
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = .6,
  out.width = "90%",
  message = F,
  #echo = F,
  warning = F
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## lists

You can put anything in a list.

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
  mat = matrix(1:8, nrow = 2, ncol = 4),
  summary = summary(rnorm(100))
)

```

```{r}
l

# gives the same results: 5 6 7 8
l$vec_numeric
l[[1]]
l[["vec_numeric"]]

l[["vec_numeric"]][1:3]
```

## `for` loop

Create a new list

```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = .2),
    d = rnorm(20, mean = -3, sd = 1)
  )

is.list(list_norm)
```

```{r}
list_norm
```

Pause and get my old function.

```{r}
mean_and_sd = function(x) {

   if (!is.numeric(x)) {
     stop("Input must be numeric")
   }
  
  if (length(x) < 3) {
    stop("Input must have atleast three numbers") 
  }
 
  # get both mean and standard deviation 
  mean_x = mean(x)
  sd_x = sd(x)
  
  # return mean and standard deviaiton as a data frame:
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}

```

I can apply that function to each list element.

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

Let's use a for loop:

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
output[[i]] = mean_and_sd(list_norm[[i]])

}

```

## Let's try map!

```{r}
output = map(list_norm, mean_and_sd)
```

What if you want a different functions...?

```{r}
output = map(list_norm, IQR)
# map(list_norm, median)
```

