---
title: "Writing fucntion"
output: github_document
---


```{r setup, include=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = .6,
  out.width = "90%",
  message = F,
  #echo = F,
  warning = F
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec) # z-scores


```

I want a function to compute the z-sxores

```{r}
z_scores = function(x) {
  #update my function:
   if (!is.numeric(x)) {
     stop("Input must be numeric")
   }
  
  if (length(x) < 3) {
    stop("Input must have atleast three numbers") 
  }
 
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}
z_scores(x_vec)

```

Try my function o some other things: these should give errors.

```{r error=TRUE}
z_scores(3) # NA, need more numbers to calculate the standard deviation
# Error in z_scores(3) : Input must have atleast three numbers

z_scores("my name is Jeff") #error, can't take a mean of a character
# Error in z_scores("my name is Jeff") : Input must be numeric

data(mtcars) # a build-in dataset in R, it's about cars and miles/gallon
z_scores(mtcars) #error, can't coerce to type double
# Error in z_scores(mtcars) : Input must be numeric

z_scores(c(TRUE, TRUE, FALSE, TRUE)) # 0.5, 0.5, 1.5, 0.5
# Error in z_scores(c(TRUE, TRUE, FALSE, TRUE)) : Input must be numeric
```

## Multiple outputs

```{r}
mean_and_sd = function(x) {

   if (!is.numeric(x)) {
     stop("Input must be numeric")
   }
  
  if (length(x) < 3) {
    stop("Input must have atleast three numbers") 
  }
 
  # get both mean and standard deviation 
  mean_x = mean(x)
  sd_x = sd(x)
  
  # returns the value of mean and standard deviation by list()
  # list(
  #   mean = mean_x,
  #   sd = sd_x
  # )
  
  # return mean and standard deviaiton as a data frame:
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
  
  
}
```

Check that function works.

```{r}
#x_vec = rnorm(100, mean=3, sd=4)
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function.
```{r}
sim_data = 
  tibble(
    x = rnorm(100, mean = 4, sd = 3)
  )

sim_data %>%
  summarize(
   mean = mean(x),
   sd = sd(x)
  )


```


```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 4) {
  
  sim_data = 
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

sim_data %>%
  summarize(
   mean = mean(x),
   sd = sd(x)
  )
}

#gives the same outputs: overwrite the mu=3, sigma=4 in the parameters
sim_mean_sd(100,6,3)
sim_mean_sd(samp_size = 100, mu = 6, sigma = 3)
sim_mean_sd(mu = 6, samp_size = 100, sigma = 3)
```




